this time is a merge

diff --git a/.github/workflows/helm-pr.yml b/.github/workflows/helm-pr.yml
--- a/.github/workflows/helm-pr.yml
+++ b/.github/workflows/helm-pr.yml
@@ -30,6 +30,17 @@ jobs:
           echo "::error::You have modified a chart. but didnt change the Chart.yaml"
           exit 1
       
+      - name: Install Helm
+        uses: azure/setup-helm@v4    
+
+      - name: Helm Lint
+        run: |
+          helm lint charts/*
+          if [ $? -ne 0 ]; then
+            echo "Helm lint failed"
+            exit 1
+          fi
+
       - name: Comment on PR with Pre-release Instructions
         uses: actions/github-script@v7
         env:
